name: Update MALA Documentation and Tests

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the source repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Clone the target repository
      - name: Clone target repository
        run: |
          git clone https://github.com/pcagas/mala.git
          cd mala
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          BRANCH_NAME="update-test-data-version-${{ github.event.release.tag_name }}"
          git checkout -b $BRANCH_NAME

      # Step 3: Make changes (e.g., update a file with the new release version)
      - name: Update version
        run: |
          echo "New release version: ${{ github.event.release.tag_name }}" > version.txt
          git add version.txt
          git commit -m "Update version to ${{ github.event.release.tag_name }}"
          git push origin $BRANCH_NAME


      # Step 4: Push changes and create a PR
      - name: Create Pull Request
        run: |
          echo "${{ secrets.TEST_DATA_PAT }}" > token.txt

          # Authorize GitHub CLI for the current repository and
          # create a pull-requests containing the updates.
          gh auth login --with-token < token.txt
          gh pr create \
            --body "" \
            --title "chore: update scripts to $LATEST_TAG" \
            --head "$BRANCH_name" \
            --base "develop"